import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
    ]

[env]
TERM = "xterm-256color"



[font]
size = 11.0

[font.normal]
family = "SpaceMono Nerd Font"
style = "Regular"

[font.bold]
family = "SpaceMono Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[window]
padding.x = 5
padding.y = 5
decorations = "Buttonless" 
opacity = 0.8
blur = true


